image: registry.gitlab.com/kodality/gitlab-builders/ng

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
      - node_modules


stages:
  - build
  - release


build:
  stage: build
  extends: .dependencies_cache
  before_script:
    - echo "//kexus.kodality.com/repository/npm/:_authToken=$NEXUS_NPM_TOKEN" >> ~/.npmrc
    - echo "@kodality-web:registry=https://kexus.kodality.com/repository/npm/" >> ~/.npmrc
    - echo "@terminology:registry=https://kexus.kodality.com/repository/npm/" >> ~/.npmrc
  script:
    - npm install --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - "**/dist"
    expire_in: 1 hour
  only:
    - branches
    - tags

build_chef:
  stage: build
  image: docker:stable
  when: manual
  before_script:
    - docker login -u $KODALITY_NEXUS_USER -p $KODALITY_NEXUS_PASSWORD docker.kodality.com
  script:
    - cd fsh-chef
    - docker build -t docker.kodality.com/fsh-chef:latest .
    - docker push docker.kodality.com/fsh-chef:latest
  only:
    - main

publish:
  stage: release
  before_script:
    - docker login -u $KODALITY_NEXUS_USER -p $KODALITY_NEXUS_PASSWORD docker.kodality.com
  script:
    - docker build -t docker.kodality.com/terminology-web:latest .
    - docker push docker.kodality.com/terminology-web:latest
    - npm run publish
  only:
    - main

release:
  stage: release
  before_script:
    - docker login -u $KODALITY_NEXUS_USER -p $KODALITY_NEXUS_PASSWORD docker.kodality.com
  script:
    - export APP_VERSION="$CI_COMMIT_REF_NAME"
    - export APP_TAG="$CI_COMMIT_TAG"

    - docker build -t docker.kodality.com/terminology-web:$APP_VERSION --build-arg APP_VERSION=$APP_VERSION .
    - docker push docker.kodality.com/terminology-web:$APP_VERSION

    - npm run publish $APP_TAG
  only:
    - /^\d*\.\d*\.\d*$/
  except:
    - branches
