image: registry.gitlab.com/kodality-public/gitlab-builders/ng

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
      - node_modules


stages:
  - build
  - publish


build:
  stage: build
  extends: .dependencies_cache
  before_script:
    - echo "//kexus.kodality.com/repository/npm/:_authToken=$NEXUS_NPM_TOKEN" >> ~/.npmrc
    - echo "@kodality-web:registry=https://kexus.kodality.com/repository/npm/" >> ~/.npmrc
    - echo "//kexus.kodality.com/repository/npm-health/:_authToken=$NEXUS_NPM_HEALTH_TOKEN" >> ~/.npmrc
    - echo "@kodality-health:registry=https://kexus.kodality.com/repository/npm-health/" >> ~/.npmrc
  script:
    - npm install --cache .npm --prefer-offline
    - ng build -c production
  artifacts:
    paths:
      - "**/dist"
    expire_in: 1 hour
  only:
    - branches
    - tags


publish:
  stage: publish
  image: docker:stable
  before_script:
    - docker login -u $KODALITY_NEXUS_USER -p $KODALITY_NEXUS_PASSWORD docker.kodality.com
  script:
    - docker build -t docker.kodality.com/terminology-web:latest .
    - docker push docker.kodality.com/terminology-web:latest
  only:
    - main

release:
  stage: release
  image: docker:stable
  before_script:
    - docker login -u $KODALITY_NEXUS_USER -p $KODALITY_NEXUS_PASSWORD docker.kodality.com
  script:
    - export APP_VERSION="$CI_COMMIT_REF_NAME"

    - docker build -t docker.kodality.com/terminology-web:$APP_VERSION --build-arg APP_VERSION=$APP_VERSION .
    - docker push docker.kodality.com/terminology-web:$APP_VERSION
  only:
    - /^\d*\.\d*\.\d*$/
  except:
    - branches
