image: registry.gitlab.com/kodality/gitlab-builders/ng

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
      - node_modules

before_script:
  - echo "//kexus.kodality.com/repository/npm/:_authToken=$NEXUS_NPM_TOKEN" >> ~/.npmrc
  - echo "@kodality-web:registry=https://kexus.kodality.com/repository/npm/" >> ~/.npmrc

stages:
  - build
  - release


build:
  stage: build
  extends: .dependencies_cache
  script:
    - echo $CI_COMMIT_REF_NAME | grep -P '^\d*\.\d*\.\d*$' && npm version $CI_COMMIT_REF_NAME
    - npm install --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - "**/dist"
    expire_in: 1 hour
  only:
    - branches
    - tags


release latest:
  stage: release
  image: docker:stable
  before_script:
    - docker login -u $KODALITY_NEXUS_USER -p $KODALITY_NEXUS_PASSWORD docker.kodality.com
  script:
    - docker build -t docker.kodality.com/termx-web:latest .
    - docker push docker.kodality.com/termx-web:latest
  only:
    - main

release tag:
  stage: release
  image: docker:stable
  before_script:
    - docker login -u $KODALITY_NEXUS_USER -p $KODALITY_NEXUS_PASSWORD docker.kodality.com
  script:
    - export APP_VERSION="$CI_COMMIT_REF_NAME"
    - docker build -t docker.kodality.com/termx-web:$APP_VERSION .
    - docker push docker.kodality.com/termx-web:$APP_VERSION
  only:
    - /^\d*\.\d*\.\d*$/
  except:
    - branches

