name: Build

on:
  push:
    branches: [ "main" ]
    tags:
      - '*.*.*'


env:
  REGISTRY: ghcr.io  
  IMAGE_NAME: termx-web

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    permissions:
      packages: write
      contents: read

#    strategy:
#      matrix:
#        node-version: [ 18.x, 20.x, 22.x ]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v4
#        with:
#          node-version: ${{ matrix.node-version }}

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Resolve dependencies
        run: npm install

#      - name: Lint
#        run: npm run lint
#
#      - name: Test
#        run: npm test

      - name: Build
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Inspect Builder
        run: docker buildx inspect --bootstrap        

      - name: Build the Docker image
        run: docker build . --file ./Dockerfile --tag $IMAGE_NAME

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}        
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}         
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=auto

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}          
